version: "3"
services:
  capstone-client-app:
    container_name: capstone-client-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3003
    volumes:
      - .:/usr/src/app/client
      - /usr/src/app/client/node_modules
